;;; custom-post-viz.el --- Visualisations & Animations -*- lexical-binding: t no-byte-compile: t -*-

;;; Commentary:
;;; Adds advanced plotting & animation workflows to Org-Babel:
;;;   - Matplotlib PNG inline (stable default)
;;;   - Plotly HTML interactive (browser)
;;;   - Matplotlib Qt window (live zoom/pan)
;;;   - Manim animations (.mp4 / .gif)
;;;
;;; Snippets provided for copy-paste into Org blocks.

;;; Code:

;; ── Matplotlib Qt backend (live interactivity) ───────────────────────
;; Set this in a Python src block before plotting:
;;   import matplotlib
;;   matplotlib.use('Qt5Agg')
;;   import matplotlib.pyplot as plt
;; Requires: pip install PyQt5

;; ── Plotly HTML interactive export ──────────────────────────────────
;; Snippet for Org block (auto-creates HTML, open manually or via hook):
;;
;;   #+begin_src python :results file :file figs/plotly_example.html
;;   import plotly.express as px
;;   fig = px.scatter_3d(df, x='x', y='y', z='z', color='category')
;;   fig.write_html("figs/plotly_example.html", auto_open=False)
;;   return "figs/plotly_example.html"
;;   #+end_src
;;
;; Auto-open HTML after babel execution:
(defun my/org-babel-open-plotly (file)
  "If FILE is an HTML file generated by a babel block, open it in browser."
  (when (and file (string-match-p "\\.html\\'" file))
    (browse-url-of-file (expand-file-name file))))

(add-hook 'org-babel-after-execute-hook
          (lambda ()
            (let ((result (org-babel-where-is-src-block-result)))
              (when result
                (with-current-buffer (marker-buffer result)
                  (goto-char result)
                  (when (looking-at "#\\+RESULTS:")
                    (forward-line 1)
                    (when (looking-at "\\[\\[file:\\(.+\\.html\\)\\]\\]")
                      (my/org-babel-open-plotly (match-string 1)))))))))

;; ── Manim animation workflow ────────────────────────────────────────
;; Snippet for generating .mp4 in Org, then embedding with #+ATTR_HTML:
;;
;;   #+begin_src python :results file :file media/videos/480p15/MyScene.mp4
;;   from manim import *
;;   class MyScene(Scene):
;;       def construct(self):
;;           circle = Circle()
;;           self.play(Create(circle))
;;   #+end_src
;;
;; Helper to convert Manim scene to GIF (lighter for inline):
(defun my/manim-to-gif (mp4-file)
  "Convert MP4-FILE (Manim output) to GIF using ffmpeg.
Requires ffmpeg installed (winget install Gyan.FFmpeg)."
  (interactive (list (read-file-name "Manim MP4: ")))
  (let ((gif-file (concat (file-name-sans-extension mp4-file) ".gif")))
    (call-process "ffmpeg" nil nil nil
                  "-i" mp4-file
                  "-vf" "fps=15,scale=480:-1:flags=lanczos"
                  "-loop" "0"
                  gif-file)
    (message "GIF created: %s" gif-file)
    gif-file))

;; ── Global helpers for Org visualisation blocks ────────────────────
(defun my/org-insert-matplotlib-template ()
  "Insert a standard matplotlib PNG inline block."
  (interactive)
  (insert "#+begin_src python :results file :file figs/plot.png\n")
  (insert "import matplotlib.pyplot as plt\n")
  (insert "import numpy as np\n\n")
  (insert "x = np.linspace(0, 10, 100)\n")
  (insert "y = np.sin(x)\n\n")
  (insert "plt.figure(figsize=(8,4))\n")
  (insert "plt.plot(x, y)\n")
  (insert "plt.savefig('figs/plot.png')\n")
  (insert "return 'figs/plot.png'\n")
  (insert "#+end_src\n"))

(defun my/org-insert-plotly-template ()
  "Insert a Plotly HTML interactive block."
  (interactive)
  (insert "#+begin_src python :results file :file figs/plotly.html\n")
  (insert "import plotly.express as px\n")
  (insert "import pandas as pd\n\n")
  (insert "df = pd.DataFrame({'x': range(10), 'y': range(10)})\n")
  (insert "fig = px.scatter(df, x='x', y='y')\n")
  (insert "fig.write_html('figs/plotly.html')\n")
  (insert "return 'figs/plotly.html'\n")
  (insert "#+end_src\n"))

;; Keymap: C-c v = visualisation prefix
(define-prefix-command 'my/viz-prefix)
(global-set-key (kbd "C-c v") 'my/viz-prefix)
(define-key my/viz-prefix (kbd "m") #'my/org-insert-matplotlib-template)
(define-key my/viz-prefix (kbd "p") #'my/org-insert-plotly-template)

(provide 'custom-post-viz)
;;; custom-post-viz.el ends here
